### ISSUE TITLE
Release Job needs a re-run to succeed

### ISSUE THREAD

**Issue by pbrisbin** [freckle/freckle-app#159]
Currently, our haddocks fail to build on the first run of the `release` Workflow. It succeeds on re-run. For more details, and to track the eventual solution, see https://github.com/commercialhaskell/stack/issues/6270

**Comment by pbrisbin** [comment]
Fixed in https://github.com/commercialhaskell/stack/commit/a3ad79447a48ac7fb07610285ef8bd80564c6ecd, not yet released.

**Comment by chris-martin** [comment]
(I believe this is only the case for `freckle-kafka` releases now, since that's the only package we build haddocks for.)

**Comment by pbrisbin** [comment]
This fix is present in Stack v3.1.1, which seems to be [what runners get now](https://github.com/actions/runner-images/blob/ubuntu22/20240825.1/images/ubuntu/Ubuntu2204-Readme.md#haskell-tools)\*. I expect our next release to not need this rerun.

\*There was a time GitHub runners lost the pre-installed `stack`, but I guess it's back.
