### ISSUE TITLE
Add utility for unwrapping AnnotatedException HUnitFailure

### ISSUE THREAD

**Issue by chris-martin** [freckle/freckle-app#190]
Here's a utility that every `SpecHook` is going to want:

```haskell
import Control.Exception qualified
import Control.Exception.Annotated (AnnotatedException (..))
import Test.HUnit.Lang (HUnitFailure)
import Test.Hspec

unwrapAnnotatedHUnitFailure :: Spec -> Spec
unwrapAnnotatedHUnitFailure = around_ $
  Control.Exception.handle $ \AnnotatedException {exception = e} ->
    Control.Exception.throw (e :: HUnitFailure)
```

This lets `hspec` catch and pretty-print `HUnitFailure`. Without it, if you end up with an `AnnotatedException HUnitFailure`, hspec doesn't recognize it and you get ugly output.

One of these packages (probably a testing library, but `freckle-app` for now since that isn't broken out yet) should include this function.

**Comment by pbrisbin** [comment]
Love this, very elegant.

> One of these packages (probably a testing library, but `freckle-app` for now

I'm wondering if an `hspec-annotated` is warranted. I know of at least another utility (`shouldThrowAnnotated`) that would fit there. :thinking:
